In [1]:
import numpy as np
print("Numpy Version:", np.__version__)
a = np.array([1, 2, 3, 4, 5])
print(a)
print("Data Type:", a.dtype)
print("Numpy Array shape:", a.shape)
print("Numpy Array size:", a.size)

Numpy Version: 1.18.5
[1 2 3 4 5]
Data Type: int32
Numpy Array shape: (5,)
Numpy Array size: 5


In [2]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print("Numpy Array shape:", a.shape)
print("Numpy Array size:", a.size)

[[1 2 3]
 [4 5 6]]
Numpy Array shape: (2, 3)
Numpy Array size: 6


In [3]:
# Creating an Numpy Array with filled zero.
import numpy as np
a = np.zeros((3, 4))
# a = np.zeroes((rows,columns))
print(a)
print("Numpy Array size:", a.size)
print("Data Type:", a.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Numpy Array size: 12
Data Type: float64


In [21]:
x = np.zeros(shape=(5))
#x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [18]:
x = np.zeros(shape=(3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
x = np.zeros(shape=(3,4), dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [4]:
import numpy as np
a = np.arange(10,19)
print(a)

b = np.arange(10, 19, 2)
print(b)

[10 11 12 13 14 15 16 17 18]
[10 12 14 16 18]


In [3]:
import numpy as np

c = np.linspace(6, 6.3, 6)
print(c)

x = np.linspace(2,9,4)
print(x)

[6.   6.06 6.12 6.18 6.24 6.3 ]
[2.         4.33333333 6.66666667 9.        ]


In [2]:
import numpy as np
d = np.full((3, 4), 5)
# d =  np.full([3,4],5)
print(d)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [18]:
import numpy as np
e = np.random.random((3,6))
print(e)

[[0.49425045 0.61747867 0.44573464 0.09562772 0.23164    0.87771953]
 [0.260009   0.6315323  0.35164713 0.94984605 0.16127064 0.42021116]
 [0.33663254 0.01605446 0.93258701 0.63492012 0.78218692 0.36679697]]


In [11]:
import numpy as np
f = np.random.randint(3,14,6)
print(f)

[11  8  7  6  8 11]


In [4]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
a.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [8]:
a.shape = (4,2)
print(a)
# a.shape[0]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
import numpy as np
n1 = np.array([20,35])
n2 = np.array([40,50])

# stack()
np.stack([n1,n2], axis=0)

array([[20, 35],
       [40, 50]])

In [6]:
np.stack([n1,n2], axis=1)

array([[20, 40],
       [35, 50]])

In [8]:
import numpy as np
n1 = np.array([20,35])
n2 = np.array([40,50])

# vstack()
np.vstack([n1,n2])

array([[20, 35],
       [40, 50]])

In [13]:
# hstack()
np.hstack([n1,n2])

array([10, 20, 30, 30, 40, 50])

In [14]:
np.column_stack([n1,n2])

array([[10, 30],
       [20, 40],
       [30, 50]])

In [15]:
a = np.arange(24, 26)
a

array([24, 25])

In [28]:
# Creating an empty Array
a = np.array(())
print(a)
print("Data Type:", a.dtype)
print("Numpy Array shape:", a.shape)
print("Numpy Array size:", a.size)
print("The Dimension:", a.ndim)

[]
Data Type: float64
Numpy Array shape: (0,)
Numpy Array size: 0
The Dimension: 1
