In [31]:
import numpy as np
print("Numpy Version:", np.__version__)
a = np.array([1, 2, 3, 4, 5])
print(a)
print("Data Type:", a.dtype)
print("Numpy Array shape:", a.shape)
print("Numpy Array size:", a.size)
print("Dimension fo the Array:", a.ndim)

Numpy Version: 1.18.5
[1 2 3 4 5]
Data Type: int32
Numpy Array shape: (5,)
Numpy Array size: 5
Dimension fo the Array: 1


# Dimensions in Arrays

In [8]:
# 0-D Arrays
import numpy as np
x = np.array(42)
print("Value of the Array:", x)
print("Shape of Array:", x.shape)
print("Size of Array:", x.size)
print("Data Type:", x.dtype)
print("Dimension fo the Array:", x.ndim)

Value of the Array: 42
Shape of Array: ()
Size of Array: 1
Data Type: int32
Dimension fo the Array: 0


In [2]:
# 1-D Arrays
import numpy as np
x = np.array([1, 2, 3, 4, 5])
print("Value of the Array:", x)
print("Shape of Array:", x.shape)
print("Size of Array:", x.size)
print("Data Type:", x.dtype)
print("Dimension fo the Array:", x.ndim)

Value of the Array: [1 2 3 4 5]
Shape of Array: (5,)
Size of Array: 5
Data Type: int32
Dimension fo the Array: 1


In [14]:
# 2-D Arrays
import numpy as np
x= np.array([[1, 2, 3], [4, 5, 6]])
# x= np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
print("Value of the array:\n", x)
print("Shape of Array:", x.shape)
print("Size of Array:", x.size)
print("Data Type:", x.dtype)
print("Dimension fo the Array:", x.ndim)

Value of the array:
 [[1 2 3]
 [4 5 6]]
Shape of Array: (2, 3)
Size of Array: 6
Data Type: int32
Dimension fo the Array: 2


In [15]:
# 3-D Arrays
x = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
#= np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("Value of the array:\n", x)
print("Shape of Array:", x.shape)
print("Size of Array:", x.size)
print("Data Type:", x.dtype)
print("Dimension fo the Array:", x.ndim)

Value of the array:
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Shape of Array: (2, 2, 3)
Size of Array: 12
Data Type: int32
Dimension fo the Array: 3
