In [7]:
import numpy as np

# creating a NumPy Array from a Python List:

a = np.array([1,2,3,4])

print(a)
print("Typs of Array:",type(a))
print("Data Type:", a.dtype)
print("Numpy Array shape:", a.shape)
print("Numpy Array size:", a.size)

[1 2 3 4]
Typs of Array: <class 'numpy.ndarray'>
Data Type: int32
Numpy Array shape: (4,)
Numpy Array size: 4


In [38]:
# creating a NumPy Array from a Python Tuple:

a = np.array((1,2,3))

print(a)
print("Typs of Array:",type(a))
print("Data Type:", a.dtype)
print("Numpy Array shape:", a.shape)
print("Numpy Array size:", a.size)

[1 2 3]
Typs of Array: <class 'numpy.ndarray'>
Data Type: int32
Numpy Array shape: (3,)
Numpy Array size: 3


In [40]:
a[1]

2

In [15]:
# creating a NumPy Array from a Python Dict:

a = np.array({1,2,3})

print(a)

{1, 2, 3}


In [35]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Data Type:", a.dtype)
print("Numpy Array shape:", a.shape)
print("Numpy Array size:", a.size)
print("Dimension fo the Array:", a.ndim)

Data Type: int32
Numpy Array shape: (3, 3)
Numpy Array size: 9
Dimension fo the Array: 2


In [20]:
# To view the first row
a[0]

array([1, 2, 3])

In [21]:
# To view the second row
a[1]

array([4, 5, 6])

In [23]:
# To view the third row
a[2]

array([7, 8, 9])

In [31]:
# To view the first column
a[1:3]

array([[4, 5, 6],
       [7, 8, 9]])