In [13]:
import numpy as np
print(np.__version__)
a = np.array([1, 2, 3, 4, 5])
a.shape
a.size

1.18.5


5

In [14]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
a.shape
a.size

[[1 2 3]
 [4 5 6]]


6

In [15]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
x.shape
x.size

[[1 2 3]
 [4 5 6]]


6

In [16]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.shape)
x.size
print(x.shape)
a = np.zeros((3, 4))
print(a)
b = np.arange(10, 19, 2)
print(b)
c = np.linspace(6, 6.3, 6)
print(c)
d = np.full((3, 4), 5)
print(d)
e = np.random.random((3, 4))
print(e)
f = np.arange(24)
print(f)
print(a.size)
print(a.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
(2, 3)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[10 12 14 16 18]
[6.   6.06 6.12 6.18 6.24 6.3 ]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[0.28944934 0.65305506 0.18303284 0.57368381]
 [0.69219685 0.80060212 0.63658142 0.89648187]
 [0.01807983 0.38214837 0.37383349 0.7890604 ]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
12
float64
