In [40]:
# Addition of NumPy Arrays:
import numpy as np
n1 = np.array([20,35])
n2 = np.array([40,10])

# Sum of NumPy Array:
np.sum([n1,n2])


105

In [41]:
# Subscraction of NumPy Array:
np.subtract(n1,n2)

array([-20,  25])

In [42]:
# Division of Numpy Array
np.divide(n1,n2)

array([0.5, 3.5])

In [48]:
# Sqrt
np.sqrt(a)

array([3.74165739, 2.23606798])

In [46]:
# Sin
np.sin(a)

array([ 0.99060736, -0.95892427])

In [49]:
# Cos
np.cos(a)

array([0.13673722, 0.28366219])

In [50]:
# Log
np.log(a)

array([2.63905733, 1.60943791])

In [21]:
# Sum of 1st Column 
np.sum([n1,n2], axis=0)

array([60, 85])

In [20]:
np.sum([n1,n2], axis=1)

array([55, 90])

In [29]:
# Addition of NumPy Arrays in 1-D
import numpy as np
a =  np.array([14,5])
np.sum(a)
# sum(a)

19

In [30]:
b =  np.array([10,2])

In [31]:
np.subtract(a,b)

array([4, 3])

In [51]:
# Element Wise Cmparision of Array

a = np.array([1,3,5])
b = np.array([7,3,6])

np.equal(a,b)

array([False,  True, False])

In [54]:
# Compare the entire Array
np.array_equal(a,b)

False

# Aggregate Function

In [64]:
import numpy as np

a =  np.array([[2,3,3,4,5],[6,7,8,9,3]])

print("The sum of the of the Array:",np.sum(a))
print("The min value of Array:",np.min(a))
print("The max value of Array:",np.max(a))
print("The median value of Array:",np.median(a))
print("The standard division value of Array:",np.std(a))
print("The corrcoef value of Array:",np.corrcoef(a))

The sum of the of the Array: 50
The min value of Array: 2
The max value of Array: 9
The median value of Array: 4.5
The standard division value of Array: 2.280350850198276
The corrcoef value of Array: [[ 1.         -0.40001814]
 [-0.40001814  1.        ]]


# Broadcasting

In [56]:
import numpy as np

a = np.array([[1,2,3], [4,5,6]])
b = np.array([3,4,5])

print("First Array:\n", a,"\n")
print("Second Array:\n", b,"\n")

print("The sum of A & B:\n", a+b, "\n")

np.sum([a,b])

First Array:
 [[1 2 3]
 [4 5 6]] 

Second Array:
 [3 4 5] 

The sum of A & B:
 [[ 4  6  8]
 [ 7  9 11]] 



array([[ 4,  6,  8],
       [ 7,  9, 11]])

In [18]:
np.subtract(a,b)

array([[-2, -2, -2],
       [ 1,  1,  1]])

# Indexing and Slicing 

In [22]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

array([1, 2, 3])

In [39]:
print(a[0])

[1 2 3]


In [25]:
print(a[:1])

[[1 2 3]]


In [28]:
print(a[:2])

[[1 2 3]
 [4 5 6]]


In [34]:
print(a[:1,1:])

[[2 3]]


In [35]:
print(a[:,1:])

[[2 3]
 [5 6]
 [8 9]]


In [37]:
print(a[:,1:])

[[2 3]
 [5 6]
 [8 9]]


In [46]:
print(a[2:,:3])

[[7 8 9]]


# Array Manupulation

In [64]:
import numpy as np

a = np.array([1,2,3])
b = np.array([3,4,5])

print("First Array:\n", a,"\n")
print("Second Array:\n", b,"\n")

np.concatenate([a,b], axis=0)

First Array:
 [1 2 3] 

Second Array:
 [3 4 5] 



array([1, 2, 3, 3, 4, 5])

In [1]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,4,5],[7,8,9]])

np.concatenate([a,b], axis=1)

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 6, 7, 8, 9]])

In [2]:
np.concatenate([a,b], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5],
       [7, 8, 9]])

# Stack

In [29]:
import numpy as np

a = np.array([1,2,3])
b = np.array([3,4,5])

np.stack([a,b], axis=0)

array([[1, 2, 3],
       [3, 4, 5]])

In [30]:
np.stack([a,b], axis=1)

array([[1, 3],
       [2, 4],
       [3, 5]])

In [31]:
import numpy as np

a = np.array([[1,2,3],[4,5,7]])
b = np.array([[3,4,5],[9,7,1]])

np.stack([a,b], axis=0)

array([[[1, 2, 3],
        [4, 5, 7]],

       [[3, 4, 5],
        [9, 7, 1]]])

In [32]:
np.stack([a,b], axis=1)

array([[[1, 2, 3],
        [3, 4, 5]],

       [[4, 5, 7],
        [9, 7, 1]]])

# Hstack

In [64]:
import numpy as np

a = np.array([[1,2,3],[4,5,7]])
b = np.array([[3,4,5],[9,7,1]])

print("stack:")
print(np.stack([a,b], axis=0))

print("\n")

print("Horizontal stack:")
print(np.hstack([a,b]))

print("\n")

print("Vertical stack:")
print(np.vstack([a,b]))

print("\n")

print("Horizontal concat:")
print(np.concatenate([a,b], axis=0))

print("\n")

print("Vertical Concat:")
print(np.concatenate([a,b], axis=1))

print("\n")

print("Column Stack:")
np.column_stack((a,b))

stack:
[[[1 2 3]
  [4 5 7]]

 [[3 4 5]
  [9 7 1]]]


Horizontal stack:
[[1 2 3 3 4 5]
 [4 5 7 9 7 1]]


Vertical stack:
[[1 2 3]
 [4 5 7]
 [3 4 5]
 [9 7 1]]


Horizontal concat:
[[1 2 3]
 [4 5 7]
 [3 4 5]
 [9 7 1]]


Vertical Concat:
[[1 2 3 3 4 5]
 [4 5 7 9 7 1]]


Column Stack:


array([[1, 2, 3, 3, 4, 5],
       [4, 5, 7, 9, 7, 1]])

In [63]:
np.column_stack((a,b))

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 7, 9, 7, 1]])