In [40]:
# Addition of NumPy Arrays:
import numpy as np
n1 = np.array([20,35])
n2 = np.array([40,10])

# Sum of NumPy Array:
np.sum([n1,n2])


105

In [41]:
# Subscraction of NumPy Array:
np.subtract(n1,n2)

array([-20,  25])

In [42]:
# Division of Numpy Array
np.divide(n1,n2)

array([0.5, 3.5])

In [48]:
# Sqrt
np.sqrt(a)

array([3.74165739, 2.23606798])

In [46]:
# Sin
np.sin(a)

array([ 0.99060736, -0.95892427])

In [49]:
# Cos
np.cos(a)

array([0.13673722, 0.28366219])

In [50]:
# Log
np.log(a)

array([2.63905733, 1.60943791])

In [21]:
# Sum of 1st Column 
np.sum([n1,n2], axis=0)

array([60, 85])

In [20]:
np.sum([n1,n2], axis=1)

array([55, 90])

In [29]:
# Addition of NumPy Arrays in 1-D
import numpy as np
a =  np.array([14,5])
np.sum(a)
# sum(a)

19

In [30]:
b =  np.array([10,2])

In [31]:
np.subtract(a,b)

array([4, 3])

In [51]:
# Element Wise Cmparision of Array

a = np.array([1,3,5])
b = np.array([7,3,6])

np.equal(a,b)

array([False,  True, False])

In [54]:
# Compare the entire Array
np.array_equal(a,b)

False

# Aggregate Function

In [64]:
import numpy as np

a =  np.array([[2,3,3,4,5],[6,7,8,9,3]])

print("The sum of the of the Array:",np.sum(a))
print("The min value of Array:",np.min(a))
print("The max value of Array:",np.max(a))
print("The median value of Array:",np.median(a))
print("The standard division value of Array:",np.std(a))
print("The corrcoef value of Array:",np.corrcoef(a))

The sum of the of the Array: 50
The min value of Array: 2
The max value of Array: 9
The median value of Array: 4.5
The standard division value of Array: 2.280350850198276
The corrcoef value of Array: [[ 1.         -0.40001814]
 [-0.40001814  1.        ]]


# Broadcasting

In [65]:
import numpy as np

a = np.array([[1,2,4], [8,7,9]])
b = np.array([4,7,9])

np.sum([a,b])

array([[ 5,  9, 13],
       [12, 14, 18]])